# currently unused, ingredeints are sourced from RecipeNLG dataset


possible_ingredients = {
    "flaxseed oil",
    "chicken",
    "curry leaves",
    "zucchini",
    "macadamia oil",
    "milk",
    "buckwheat",
    "bay leaves",
    "mace",
    "raita",
    "rosehip oil",
    "hummus",
    "handvo",
    "chard",
    "sesame seeds",
    "naan",
    "malpua",
    "rosemary",
    "poppy seeds",
    "bread",
    "batata vada",
    "red chili powder",
    "coriander",
    "okra",
    "kofta",
    "baharat",
    "fenugreek",
    "coconut",
    "garam masala",
    "kale",
    "bhaat",
    "jaggery",
    "celery",
    "mint",
    "mutton masala",
    "ginger",
    "grape",
    "lotus root",
    "raspberry",
    "curry powder",
    "water chestnut",
    "spinach",
    "sev mamra",
    "dhokli",
    "aamras",
    "bay leaf",
    "peach",
    "masala",
    "pedha",
    "laddu",
    "rasmalai",
    "walnut oil",
    "jojoba oil",
    "dukkah",
    "peanut oil",
    "eggplant",
    "panch phoron",
    "cocoa butter",
    "paratha",
    "gathiya",
    "avocado butter",
    "halva",
    "green onion",
    "black salt",
    "lime",
    "ghee",
    "kachori",
    "onion",
    "shea butter",
    "cucumber",
    "cassava",
    "potato",
    "pasta",
    "fennel",
    "spaghetti squash",
    "noodles",
    "barley",
    "bulgur",
    "imarti",
    "oregano",
    "khaman",
    "petha",
    "cashew oil",
    "patra",
    "couscous",
    "broccoli",
    "pumpkin",
    "shrikhand",
    "blueberry",
    "mathiya",
    "tabbouleh",
    "coriander seeds",
    "bajri no rotlo",
    "coconut oil",
    "tahini",
    "cayenne",
    "kulfi",
    "almond oil",
    "grapeseed oil",
    "olive oil",
    "fish",
    "puran poli",
    "cinnamon",
    "ras el hanout",
    "sunflower butter",
    "undhiyu",
    "snap pea",
    "sheera",
    "fulwadi",
    "millet",
    "cashew butter",
    "avocado",
    "mohanthal",
    "biryani masala",
    "sunflower oil",
    "sweet potato",
    "lemon",
    "tomato",
    "meat masala",
    "ajwain",
    "cabbage",
    "chapati",
    "bell pepper",
    "pav bhaji masala",
    "pumpkin seed butter",
    "khichu",
    "yam",
    "apple",
    "mango butter",
    "mustard seed",
    "tamarind",
    "butter",
    "muthia",
    "turnip",
    "kheer",
    "bean sprout",
    "kesar shrikhand",
    "canola oil",
    "saffron",
    "cardamom",
    "black cardamom",
    "parsley",
    "vada pav masala",
    "butternut squash",
    "baklava",
    "pineapple",
    "hemp oil",
    "pork",
    "farali",
    "walnut butter",
    "avocado oil",
    "khakra",
    "dal",
    "artichoke",
    "flour",
    "shankarpali",
    "blackberry",
    "argan oil",
    "fafda",
    "pepper",
    "fish masala",
    "nutmeg",
    "cumin seeds",
    "malabar masala",
    "turmeric",
    "ghari",
    "khandvi",
    "farro",
    "saag",
    "dabeli",
    "star anise",
    "idli podi",
    "green bean",
    "safflower oil",
    "salt",
    "sesame oil",
    "cream",
    "modak",
    "sambar powder",
    "snow pea",
    "jicama",
    "beef",
    "sumac",
    "thyme",
    "radish",
    "sesame butter",
    "asafoetida",
    "habanero",
    "dal tadka",
    "garlic",
    "banana",
    "falafel",
    "korma",
    "rutabaga",
    "fennel seeds",
    "za'atar",
    "chili pepper",
    "amchoor",
    "rice bran oil",
    "dolma",
    "beetroot",
    "tea tree oil",
    "mango",
    "sugar",
    "cheese",
    "rasam powder",
    "oats",
    "paprika",
    "green cardamom",
    "brussels sprouts",
    "vegetable oil",
    "almond paste",
    "coconut butter",
    "rice",
    "tagine",
    "rajma",
    "cumin",
    "almond butter",
    "chicken masala",
    "roti",
    "papad",
    "dal dhokli",
    "amaranth",
    "egg",
    "quinoa",
    "cilantro",
    "yogurt",
    "lassi",
    "peanut butter",
    "shawarma",
    "pear",
    "cloves",
    "serrano",
    "tamarind paste",
    "corn oil",
    "laddoo",
    "paneer",
    "cauliflower",
    "green chili",
    "mustard oil",
    "taros",
    "rasgulla",
    "hazelnut butter",
    "pita bread",
    "strawberry",
    "thandai",
    "chutney",
    "bamboo shoot",
    "polenta",
    "castor oil",
    "acorn squash",
    "dal fry",
    "carrot",
    "soybean oil",
    "basil",
    "kasuri methi",
    "chaat masala",
    "coconut milk",
    "basundi",
    "jalapeno",
    "labneh",
    "asparagus",
    "orange",
    "harissa",
    "oil",
    "sandesh",
    "bhakri",
    "biriyani",
    "vegetable biryani",
    "coconut cream",
    "lettuce",
    "srikhand",
}
